# 25/11/2022

- image   : sebastien-deleersnyder.jpg
  day     : 25/11/2022
  time    : 09:00 - 17:00
  name    : Sebastien Deleersnyder
  bio     : >-
            Sebastien (Seba) Deleersnyder is co-founder and CTO of Toreon.
            He is also COO and head threat modeling trainer at Data Protection
            Institute. He started the Belgian OWASP chapter and was an OWASP
            Foundation Board member. With a development background and years
            of security experience, he has trained countless developers to
            create more secure software. Leading OWASP projects such as OWASP
            SAMM, he has genuinely helped make the world a safer place.
            What’s he currently up to? Right now, he’s busy adapting application
            security models to the evolving field of DevOps and is also focused
            on getting the word out on Threat Modeling to a broader audience.
  title   : OWASP SAMM
  abstract: >-
            Building security into the software development and management practices of an organisation can be a daunting task. There are many factors that must be considered when charting your path forward, inlcuding&#58; company structure, stakeholder priorities, technology stacks, tools and processes, and existing technical debt.<br />
            <br />
            Implementing software assurance can produce significant benefits for the organisation. However, trying to achieve this without a good framework often yields only marginal and unsustainable improvements. OWASP SAMM (<a href="https://owaspsamm.org/">https://owaspsamm.org/</a>) provides exactly the structured, measurable framework that's needed. It enables you to formulate and implement a strategy for software security tailored to your organisation's risk profile.<br />
            <br />
            This one-day training is organised as a mix of presentations and interactive workshops. Our goal is for participants to get an in-depth view of, and practical feel for, the OWASP SAMM model. The session is organised in three parts&#58;<br />
            <ul>
            <li>First, we present an overview of the model and review the similarities and differences with other models. The five Business Functions - Governance, Design, Implementation, Verification, and Operations - are explained. We address the various constituent elements (e.g., metrics), review representative usage scenarios for the model, and defining an assessment's scope.</li>
            <li>The majority of our day will be spent reviewing the Security Practices comprising each Business Function, with an emphasis on assessing your organisation's maturity. Each Practice's treatment will include a hands-on segment, providing you an opportunity to apply SAMM to your organisation (or one you have worked for). We will assess representative Activities across all SAMM Practices, discussing our results and concerns in the group. This will give participants a good indication of their organisations’ maturity in software assurance. In the same effort, we will define a target model for your organisation and identify the most important challenges in getting there.</li>
            <li>The final part of the training will be dedicated to specific questions or challenges that you are facing about secure development in your organisation. In this group discussion, experiences will be shared among participants to address these questions.</li>
            </ul>
            If you've been struggling to launch a secure software initiative in your organisation, this training should provide you with the necessary foundations and ideas to do so.<br />
            <br />
            SAMM training outline<br />
            <ul>
            <li>Introductions and Class Overview</li>
            <li>The "Application Security Problem"</li>
            <li>Software Development Lifecycle (SDLC) Overview</li>
            <li>SAMM - Vision, History, Structure</li>
            <li>SAMM as an Assessment Tool</li>
            <li>Establishing Assessment Scope</li>
            <li>Methodology - Assessment and Roadmapping</li>
            <li>Assessing Governance
              <ul>
                  <li>Strategy & Metrics</li>
                  <li>Policy & Compliance</li>
                  <li>Education & Guidance</li>
              </ul>
            </li>
            <li>Assessing Design
              <ul>
                  <li>Threat Assessment</li>
                  <li>Security Requirements</li>
                  <li>Security Architecture</li>
              </ul>
            </li>
            <li>Assessing Implementation
              <ul>
                  <li>Secure Build</li>
                  <li>Secure Deployment</li>
                  <li>Defect Management</li>
              </ul>
            </li>
            <li>Assessing Verification
              <ul>
                  <li>Architecture Assessment</li>
                  <li>Requirements-driven Testing</li>
                  <li>Security Testing</li>
              </ul>
            </li>
            <li>Assessing Operations
              <ul>
                  <li>Incident Management</li>
                  <li>Environment Management</li>
                  <li>Operational Management</li>
              </ul>
            </li>
            <li>Setting Improvement Targets</li>
            <li>OWASP SAMM Tools
              <ul>
                  <li>Assessment Toolkit</li>
                  <li>SAMMwise</li>
                  <li>SAMM Benchmark Project</li>
                  <li>Integration with Other OWASP Projects & Tools</li>
              </ul>
            </li>
            <li>SAMM Best Practices
              <ul>
                  <li>Choosing the Right Starting Points</li>
                  <li>Monitoring and Metrics</li>
                  <li>Achieving Security by Default</li>
                  <li>Critical Success Factors</li>
              </ul>
            </li>
            <li>Wrap-up
              <ul>
                <li>Conclusions</li>
                <li>Looking Forward</li>
                <li>Getting Involved</li>
              </ul>
            </li>
            </ul>
  feed    :
  url     :
  urltag  :
  display : yes

- image   : jeroen-beckers.jpeg
  day     : 25/11/2022
  time    : 09:00 - 17:00
  name    : Jeroen Beckers
  bio     : >-
            I am the mobile solution lead at NVISO, where I am responsible for
            quality delivery, innovation and methodology for all mobile
            assessments. I am actively involved in the mobile security
            community, and I try to share my knowledge through open-source
            tools, blogposts, trainings and presentations. ​I am the lead
            author and instructor of the SANS 575 course: Mobile device
            security and ethical hacking and a co-author of the OWASP Mobile
            Application Security Testing Guide (MSTG) and OWASP Mobile
            Application Security Verification Standard (MASVS).
  title   : OWASP Mobile Application Security (MAS / MASVS / MASTG)
  abstract: >-
            Every day you walk around with a smartphone that contains your most
            intimate secrets. Or maybe just your boring work emails. In any
            case, that data needs to be properly protected. The OWASP Mobile
            Application Security (MAS) project contains the OWASP Mobile
            Application Security Verification Standard (MASVS) and the OWASP
            Mobile Application Security Testing Guide (MASTG) which provide
            practical security controls that can be implemented to develop
            secure applications.<br><br>
            In this workshop, participants will come in contact with the basics
            of mobile application security. Through hands-on exercises, Jeroen
            will show which mistakes can be made, both at the design and
            implementation level, that can compromise the security of both
            the application and the backend server. Although no real prior
            experience with mobile applications is needed, some basic knowledge
            on programming is advised. All exercises are performed on the
            Corellium platform and no physical testing devices are required.
  feed    :
  url     :
  urltag  :
  display : yes

- image   : brenno-de-winter.jpg
  day     : 25/11/2022
  time    : 09:00 - 17:00
  name    : Brenno de Winter
  bio     : >-
            Brenno de Winter, 1971, wrote his first software at the age of 5.
            He has been in IT ever since. From 2001 to 2016 he was an
            investigative journalist on technology issues and became journalist
            of the year for hacking the public transportion rfid-cards. Sinds
            may 2020 he is Chief Security and Privacy Operations at the Dutch
            Ministry of Health, Welfare and Sport for the program Realisation
            Digital Support COVID19.
  title   : Hurding OpenKAT
  abstract: >-
            OpenKAT is a monitoring tool and vulnerability scanner created by
            the Dutch Ministry of Health during the vaccination campaign. New
            systems and functions were developed at high speed and monitoring
            was needed.<br><br>
            OpenKAT combines information from different sources and tools,
            scans automatically and allows for broad analysis and vulnerability
            detection. It is a modular framework for automagic monitoring or
            larger systems.<br><br>
            OpenKAT is useful if you have a complex or large system and a wish
            to know if there are vulnerabilities and configuration mistakes
            hiding somewhere. Most security incidents are caused by known
            vulnerabilities and small errors. OpenKAT finds them before they
            are found.<br><br>
            In this training you learn the innerworkings of OpenKAT and you will
            make your first 'boefje' and 'bit' to integrate OWASP-tools within
            KAT.
  feed    :
  url     :
  urltag  :
  display : yes

- image   : filip-chyla.jpg
  image2  : marinus-kuivenhoven.jpg
  day     : 25/11/2022
  time    : 09:00 - 17:00
  name    : Filip Chyla 
  name2   : Marinus Kuivenhoven
  bio     : >-
            Filip has worked in IT for over 15 years, 8 of those years in 
            cybersecurity with a focus on infrastructure and cloud security. 
            Currently part of Xebia Security helping customers on their cloud 
            journeys by using security to enable the organization to grow 
            securely and most productively. His specialties are DevSecOps and 
            cloud security. He likes to spend time researching new technologies 
            in the cloud. Designing, analysing cloud environments and finding 
            cloud integration with existing infrastructure. He’s passionate 
            about using the defensive and offensive sides of security to bring 
            additional value to projects he is involved in. Prior to joining 
            Xebia, Filip worked at FlowTraders as a security engineer, helping 
            with the cloud transformation and working to secure their 
            high-speed trading environments.Marinus works as a CTO and head of 
            learning and coaching at Xebia Security. He has 20 years of 
            experience in implementing security in the culture, teams and 
            development life cycles at organizations. But also, the underlying 
            activities like security requirements, architectural threat analysis, 
            source code reviews, social engineering, penetration testing, and red 
            teaming.
  bio2    : >-
            Marinus also developed several courses on security and has given them 
            to well over 5000 participants. Lastly, Marinus has helped many 
            organizations to raise their maturity level of security in the most 
            efficient way. Clients include major players in the retail, wholesale, 
            insurance, telecommunication and transport industries as well as the 
            Dutch government.
  title   : Securing DevOps pipelines
  abstract: >-
            DevOps forces the business and AppSec to start interacting differently 
            with development teams. Many security(-related) processes were never 
            designed for a high-velocity development environment which leads to 
            ineffective and time-consuming processes. In order to instead make 
            them add value we need rethink and redesign these processes in such a 
            way that DevSecOps frees the team from the impactful activities that 
            are on top of their existing way of working.<br />  
            Automating and off-loading security activities allow for a development 
            team to focus on adding value. At the same time through the use of 
            Infrastructure as Code and Immutability it is possible to remove human 
            error from common or impactful tasks. This training shows how to 
            integrate security in the development proces, platform, product and 
            pipelines.
  feed    :
  url     :
  urltag  :
  display : yes
