# 25/11/2022

# - image   : image.jpg
#   day     : 25/11/2023
#   time    : 09:00 - 17:00
#   name    : Trainer
#   bio     : >-
#             Biography
#   title   : Training title
#   abstract: >-
#             Training description
#   feed    :
#   url     :
#   urltag  :
#   display : yes
